### ISSUE TITLE
Please clarify Found vs Discovered

### ISSUE THREAD

**Issue by gisborne** [DarkerWaters/flic_button#13]
I've spent a while spelunking your code and that of the original flic lib. I'm not clear what the difference is between "found" and "discovered".

I'd be grateful if you could add some notes in the readme and the docs for the relevant functions about the difference.

**Comment by butterbrain** [comment]
You could just treat them as the same thing, but looking at the Flic2
documentation, it looks like 'Found' is kicked off from the

onDiscoveredAlreadyPairedButton

function in the Java documentation. So it looks like found is called when
there is a button already paired and the API returns its data. Discovered
would be returned with just the ID on a scan, so a new button that isn't
paired yet?

Hope this helps... I didn't really look into any difference as just wrapped
the APIs and did what I did without worrying about it (O:
