### ISSUE TITLE
Upload of iOS version to App Store fails: Lib contains bitcode

### ISSUE THREAD

**Issue by komaxx** [DarkerWaters/flic_button#15]
When trying to upload a new version built with XCode 16 for iOS 18 to the App Store, I've received an error message:

```
Asset validation failed (90482)
Invalid Executable. The executable 'Runner.app/Frameworks/flic3lib.framweork/flick2lib' contains bitcode.
```

There's an updated framework available from 50ButtonsEach. Will create a pull request with the updated framework!

**Comment by butterbrain** [comment]
I merged your changes (looked good) and will publish an update

**Comment by komaxx** [comment]
Thank you so much!

**Comment by butterbrain** [comment]
1.2.4 uploaded - I'll compile my dependent app to see if it works - let me
know if you have any problems and I can try to fix... The flic2 libraries
are a bit of a pain as they include alias 'simlinks' which you can't
publish to pub.dev so I have to copy over the 'real' files by hand which
always worries me )O:

**Comment by komaxx** [comment]
Looks good on my end! Thank you again :)
