### ISSUE TITLE
[Android] OnScanCompleted callback when starting scan

### ISSUE THREAD

**Issue by komaxx** [DarkerWaters/flic_button#5]
When I use the plugin to start a Flic button scan on Android, I immediately get a callback to `onScanCompleted`.
I can work around that by keeping track myself and only consider scanning active if there was a `onScanStarted` callback before the `onScanCompleted` - but I'd still consider this a bug.

Desired behavior:
Only call `onScanCompleted` if there was actually a scan that finished.

**Comment by butterbrain** [comment]
Thanks Matthias,

I changed it a bit so the Flic2 plugin tries to cancel the connections each
time it starts (as flic handles the running state itself and might be more
robust if it fails for some reason) but only sends the completed message if
your added flag is true.

Thanks for that - I published 1.1.1 if you want to update and use the
official version in your code.

It's lovely that someone is using my plugin - very rewarding (O:

**Comment by komaxx** [comment]
Hi Douglas,
thank you for the merge and for improving on the PR!
